name: boardops
description: BoardOps Flutter application foundation.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.13.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 3.4.2
  go_router: 18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
